export const INDUSTRIES = [
    "Medical / Healthcare",
    "Hotels / Restaurants",
    "Retail / FMCG",
    "Automobile",
    "Construction",
    "BPO / Customer Services",
    "Sales & Marketing",
    "Education & Training",
    "Engineering & Technical",
    "Textile Manufacturing",
    "Small – scale Manufacturing",
    "Textiles & Garments",
    "MSME",
    "Start-Ups",
];

export const FIELD_NAMES = [
    { key: "fullName", label: "Full Name" },
    { key: "email", label: "Email" },
    { key: "phone", label: "Phone" },
    { key: "gender", label: "Gender" },
    { key: "dateOfBirth", label: "Date of Birth" },
    { key: "currentLocation", label: "Current Location" },
    { key: "preferredWorkLocation", label: "Preferred Work Location" },
    { key: "totalExperience", label: "Total Experience" },
    { key: "currentCompany", label: "Current Company" },
    { key: "currentDesignation", label: "Current Designation" },
    { key: "currentSalary", label: "Current Salary" },
    { key: "expectedSalary", label: "Expected Salary" },
    { key: "noticePeriod", label: "Notice Period" },
    { key: "highestQualification", label: "Highest Qualification" },
    { key: "specialization", label: "Specialization" },
    { key: "university", label: "University" },
    { key: "keySkills", label: "Key Skills" },
    { key: "preferredJobType", label: "Preferred Job Type" },
    { key: "linkedinProfile", label: "LinkedIn Profile" },
    { key: "portfolio", label: "Portfolio" },
    { key: "resumeUrl", label: "Resume Upload" },
];
